name: Medical Physics Notes by Deepwhiter
markdown: kramdown
permalink: /:year/:month/:day/:title 
site.title: A Medical Physicst 
timezone: America/New_York
subscribe: http://deepwhiter.github.io/feed.xml
githubEditBaseURL: https://github.com/deepwhiter/deepwhiter.github.io/edit/master/
disqusShortname: Medical Physics Notes
