name: Deepwhiter
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: Deepwhiter
timezone: America/New_York
subscribe: http://deepwhiter.github.io/feed.xml
githubEditBaseURL: https://github.com/deepwhiter/deepwhiter.github.io/edit/master/
disqusShortname: DP